#!/usr/bin/env python

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

TRANSLATOR_MODEL_ID = "facebook/nllb-200-distilled-1.3B"
TRANSLATOR_MODEL_CACHE = "translator-model-cache"
TRANSLATOR_TOKENIZER_CACHE = "translator-tokenizer-cache"

# For the translator
print("Downloading translation models...")
translate_tokenizer = AutoTokenizer.from_pretrained(TRANSLATOR_MODEL_ID,  cache_dir=TRANSLATOR_TOKENIZER_CACHE)
translate_model = AutoModelForSeq2SeqLM.from_pretrained(
    TRANSLATOR_MODEL_ID,
    cache_dir=TRANSLATOR_MODEL_CACHE
)

        